// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: transport/internet/phantom/config.proto

package phantom

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Config is the Phantom security protocol configuration.
// Phantom is a simplified, easy-to-use fork of REALITY that supports
// password-based authentication (no manual key generation required) and
// optional traffic padding to resist DPI fingerprinting.
type Config struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Show debug logs when true.
	Show bool `protobuf:"varint,1,opt,name=show,proto3" json:"show,omitempty"`
	// Dest is the fallback destination address (e.g. "example.com:443").
	Dest string `protobuf:"bytes,2,opt,name=dest,proto3" json:"dest,omitempty"`
	// Type is the network type of the fallback destination ("tcp" or "unix").
	Type string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	// Xver is the PROXY protocol version to use when connecting to dest (0, 1, or 2).
	Xver uint64 `protobuf:"varint,4,opt,name=xver,proto3" json:"xver,omitempty"`
	// ServerNames is the list of allowed SNI values on the server.
	ServerNames []string `protobuf:"bytes,5,rep,name=server_names,json=serverNames,proto3" json:"server_names,omitempty"`
	// PrivateKey is the X25519 private key used for server authentication.
	// If empty and Password is set, derived automatically from Password.
	PrivateKey []byte `protobuf:"bytes,6,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	// ShortIds are the allowed short IDs used in the client hello.
	ShortIds [][]byte `protobuf:"bytes,10,rep,name=short_ids,json=shortIds,proto3" json:"short_ids,omitempty"`
	// Fingerprint is the uTLS fingerprint to use (e.g. "chrome", "firefox").
	// Defaults to "chrome" when empty.
	Fingerprint string `protobuf:"bytes,21,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	// ServerName is the SNI to present to the server.
	ServerName string `protobuf:"bytes,22,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	// PublicKey is the X25519 public key of the server.
	// If empty and Password is set, derived automatically from Password.
	PublicKey []byte `protobuf:"bytes,23,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// ShortId is the short ID expected by the server.
	ShortId []byte `protobuf:"bytes,24,opt,name=short_id,json=shortId,proto3" json:"short_id,omitempty"`
	// Password is used to derive the X25519 key pair automatically.
	// Set the same password on both server and client for zero-config key
	// exchange. If PrivateKey/PublicKey are also set they take precedence.
	Password string `protobuf:"bytes,30,opt,name=password,proto3" json:"password,omitempty"`
	// Padding enables random traffic padding to resist DPI traffic-size
	// fingerprinting. Recommended to enable for maximum obfuscation.
	Padding bool `protobuf:"varint,31,opt,name=padding,proto3" json:"padding,omitempty"`
	// MasterKeyLog is a path to write TLS master secrets for debugging.
	MasterKeyLog string `protobuf:"bytes,32,opt,name=master_key_log,json=masterKeyLog,proto3" json:"master_key_log,omitempty"`
	// SpiderX is the spider starting path with optional query parameters that
	// control spider behaviour (same syntax as REALITY's spiderX):
	//
	//	?p=<min>-<max>   cookie padding length
	//	?c=<min>-<max>   concurrent sub-requests
	//	?t=<min>-<max>   page load repeats
	//	?i=<min>-<max>   interval between repeats (ms)
	//	?r=<min>-<max>   return-delay after verification failure (ms)
	//
	// Defaults to "/" when empty.
	SpiderX string `protobuf:"bytes,33,opt,name=spider_x,json=spiderX,proto3" json:"spider_x,omitempty"`
	// SpiderY stores the parsed integer bounds from SpiderX at index positions:
	//
	//	[0,1]  padding, [2,3] concurrency, [4,5] times, [6,7] interval, [8,9] return
	SpiderY       []int64 `protobuf:"varint,34,rep,packed,name=spider_y,json=spiderY,proto3" json:"spider_y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_transport_internet_phantom_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_transport_internet_phantom_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_transport_internet_phantom_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetShow() bool {
	if x != nil {
		return x.Show
	}
	return false
}

func (x *Config) GetDest() string {
	if x != nil {
		return x.Dest
	}
	return ""
}

func (x *Config) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Config) GetXver() uint64 {
	if x != nil {
		return x.Xver
	}
	return 0
}

func (x *Config) GetServerNames() []string {
	if x != nil {
		return x.ServerNames
	}
	return nil
}

func (x *Config) GetPrivateKey() []byte {
	if x != nil {
		return x.PrivateKey
	}
	return nil
}

func (x *Config) GetShortIds() [][]byte {
	if x != nil {
		return x.ShortIds
	}
	return nil
}

func (x *Config) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *Config) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *Config) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *Config) GetShortId() []byte {
	if x != nil {
		return x.ShortId
	}
	return nil
}

func (x *Config) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Config) GetPadding() bool {
	if x != nil {
		return x.Padding
	}
	return false
}

func (x *Config) GetMasterKeyLog() string {
	if x != nil {
		return x.MasterKeyLog
	}
	return ""
}

func (x *Config) GetSpiderX() string {
	if x != nil {
		return x.SpiderX
	}
	return ""
}

func (x *Config) GetSpiderY() []int64 {
	if x != nil {
		return x.SpiderY
	}
	return nil
}

var File_transport_internet_phantom_config_proto protoreflect.FileDescriptor

const file_transport_internet_phantom_config_proto_rawDesc = "" +
	"\n" +
	"'transport/internet/phantom/config.proto\x12\x1fxray.transport.internet.phantom\"\xc8\x03\n" +
	"\x06Config\x12\x12\n" +
	"\x04show\x18\x01 \x01(\bR\x04show\x12\x12\n" +
	"\x04dest\x18\x02 \x01(\tR\x04dest\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x12\n" +
	"\x04xver\x18\x04 \x01(\x04R\x04xver\x12!\n" +
	"\fserver_names\x18\x05 \x03(\tR\vserverNames\x12\x1f\n" +
	"\vprivate_key\x18\x06 \x01(\fR\n" +
	"privateKey\x12\x1b\n" +
	"\tshort_ids\x18\n" +
	" \x03(\fR\bshortIds\x12 \n" +
	"\vfingerprint\x18\x15 \x01(\tR\vfingerprint\x12\x1f\n" +
	"\vserver_name\x18\x16 \x01(\tR\n" +
	"serverName\x12\x1d\n" +
	"\n" +
	"public_key\x18\x17 \x01(\fR\tpublicKey\x12\x19\n" +
	"\bshort_id\x18\x18 \x01(\fR\ashortId\x12\x1a\n" +
	"\bpassword\x18\x1e \x01(\tR\bpassword\x12\x18\n" +
	"\apadding\x18\x1f \x01(\bR\apadding\x12$\n" +
	"\x0emaster_key_log\x18  \x01(\tR\fmasterKeyLog\x12\x19\n" +
	"\bspider_x\x18! \x01(\tR\aspiderX\x12\x19\n" +
	"\bspider_y\x18\" \x03(\x03R\aspiderYB\x7f\n" +
	"#com.xray.transport.internet.phantomP\x01Z4github.com/xtls/xray-core/transport/internet/phantom\xaa\x02\x1fXray.Transport.Internet.Phantomb\x06proto3"

var (
	file_transport_internet_phantom_config_proto_rawDescOnce sync.Once
	file_transport_internet_phantom_config_proto_rawDescData []byte
)

func file_transport_internet_phantom_config_proto_rawDescGZIP() []byte {
	file_transport_internet_phantom_config_proto_rawDescOnce.Do(func() {
		file_transport_internet_phantom_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transport_internet_phantom_config_proto_rawDesc), len(file_transport_internet_phantom_config_proto_rawDesc)))
	})
	return file_transport_internet_phantom_config_proto_rawDescData
}

var file_transport_internet_phantom_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_transport_internet_phantom_config_proto_goTypes = []any{
	(*Config)(nil), // 0: xray.transport.internet.phantom.Config
}
var file_transport_internet_phantom_config_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_transport_internet_phantom_config_proto_init() }
func file_transport_internet_phantom_config_proto_init() {
	if File_transport_internet_phantom_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transport_internet_phantom_config_proto_rawDesc), len(file_transport_internet_phantom_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_transport_internet_phantom_config_proto_goTypes,
		DependencyIndexes: file_transport_internet_phantom_config_proto_depIdxs,
		MessageInfos:      file_transport_internet_phantom_config_proto_msgTypes,
	}.Build()
	File_transport_internet_phantom_config_proto = out.File
	file_transport_internet_phantom_config_proto_goTypes = nil
	file_transport_internet_phantom_config_proto_depIdxs = nil
}
